### PR TITLE
qt4-mac: update to 4.8.7 with Tiger patches

### PR DESCRIPTION
**Pull request by devernay**
Starting from the qt4-mac 4.8.7 port, I patched a few things to be able to compile and run on Tiger.

All the tiger-specific patches are suffixed with -tiger, and don't break anything with more recent SDKs. Only one patch, `patch-src_gui_dialogs_qfontdialog_mac.mm-tiger.diff`, reintroduces a Qt bug (QTBUG-27415) which cannot be fixed with the Tiger SDK (the fix requires Leopard).

### CODE REVIEW

**Comment by devernay** [comment]
This was also submitted upstream, so hopefully the pin may be removed:
https://github.com/macports/macports-ports/pull/740

**Comment by kencu** [comment]
Thanks! I think someone like you might also be interested in this <https://github.com/kencu/LeopardPorts/tree/master/lang/llvm-3.8> reasonably nicely working clang-3.8 for PPC I've been working on.

**Comment by kencu** [comment]
If you do decide to try clang, this is of interest <https://lists.macports.org/pipermail/macports-dev/2017-June/035874.html>. The rt_runtime cmake script is not quite perfect, so needs some manual intervention at one point until I fix it.

**Comment by devernay** [comment]
Hi Ken, I've added Tiger support back to webkit in Qt 4.8.7.
I will test tomorrow on my G4 to see if it still crashes
https://github.com/devernay/TigerPorts/tree/qt4-487

Note: perhaps this patch could be used to bring Tiger support to Leopard Webkit...

**Comment by devernay** [comment]
About clang: I use exceptions a lot in my C++ code so I guess clang on PPC is still a no-go
Why not stick to a recent GCC instead?
I even made something to be able to build universal binaries with any GCC.
Check out https://github.com/devernay/macportsGCCfixup

Unfortunately, it seems like GCC 7.2 from MacPorts is not compiling on PPC/Darwin (did you check that?)
GCC 6.4 was OK, so I guess we could pin the GCC ports before https://github.com/macports/macports-ports/commit/ff4c4bd6219f166b85c82c44eecb909dd3ae08b3

**Comment by kencu** [comment]
great work! will check. Leopard supports qt4-mac 4.8.7 now on Macports. I do use gcc6 a lot on Tiger and Leopard PPC with excellent results -- some ObjC it can't handle tho.

Your talents are much appreciated!

**Comment by devernay** [comment]
just tested my latest patch-webkit-tiger.diff (which I just pushed), and designer and assistant now work. It was just a matter of reviving that "dead code", after all

**Pull request merged**
